# Project metadata
name: mobile_dice_rolling
description: "A Flutter application for dice rolling simulations."
publish_to: 'none' # Prevents accidental publishing to pub.dev

# Version information
# format: major.minor.patch+build_number
version: 1.0.0+1

# Environment constraints
environment:
  sdk: ^3.7.2 # Dart SDK version

# Package dependencies
dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
    
  # UI related
  flutter_svg: ^2.0.7    # SVG rendering support
  
  # State management
  provider: ^6.1.5        # State management solution
  
  # Audio and media
  audioplayers: ^5.2.1    # Alternative audio player
  
  # Data and utilities
  intl: ^0.20.2           # Internationalization and localization
  shared_preferences: ^2.5.3  # Local data persistence
  url_launcher: ^6.1.12   # Opening URLs in browsers

# Development dependencies
dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    
  # Code quality
  flutter_lints: ^5.0.0   # Recommended lint rules

# Flutter-specific configuration
flutter:
  # Material Design
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/icons/     # Dice and UI icons
    - assets/sounds/    # Dice rolling and other sound effects

  # Uncomment and modify as needed for custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
